# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - run: npm install
    - run: npm install chromedriver 
    - run: npm install chrome -g
    - run: npm install --save chrome-version
    
    - run: npm run build --if-present
    - run: npx webdriver-manager update
    - run: npm install protractor
    - run: npm audit fix --force 
    - run: npm run apitests
      env:
        CI: true
        BROWSER: chrome
